INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1971-09-24', 1, null, null, 'هرمز', 'عباس', ' روستایی', '1829067400', null, null, '824',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1971-07-30', 1, null, null, 'نادر', 'محمد رضا ', 'محمد رضایی', '1829358103', null, null, '703',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1978-04-18', 1, null, null, 'بهروز', 'روزبه', ' کسری', '0069201323', null, null, '785',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1986-12-10', 1, null, null, 'محمد', 'ناصر ', 'روستائی', '3934652395', null, null, '249',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1986-06-18', 1, null, null, 'بهروز', 'علی ', ' کسری', '0080110071', null, null, '17411',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1976-03-17', 1, 'اصفهان خیابان وحید کوچه راست قلم بن بست لاله', null, 'محمود', 'حسین', ' یزدانی ', '1170260489', null, '8173983581', '1639',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1974-05-28', 1, 'اصفهان خیابان وحید کوچه راست قلم بن بست لاله', null, 'محمود', 'محسن', ' یزدانی کچوئی', '1171053010', null, '8173983581', '8',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES (null, 1, null, null, null, 'حمید رضا', ' نساج پور اصفهانی', '1287166229', null, null, null,now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1968-11-06', 1, 'اصفهان خیابان ارتش کوچه خدا رحمی پلاک43', null, 'محمود', 'محمد', ' یزدانی کچوئی', '4722905517', null, '8174749435', '21715',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1952-01-23', 1, 'اصفهان خیابان توحید کوی یساولیان خیایان بهار آزادی پلاک 2', null, 'سید ناصر', 'سید مصطفی', ' عطائی کچوئی', '1170848265', null, '8471866336', '22',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES (null, 1, null, null, 'سید مصطفی', 'سید محمود', ' عطائی کچوئی', '1171246579', null, null, null,now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES (null, 1, null, null, 'سید مصطفی', 'سید محمد', ' عطائی کچوئی', '1170260640', null, null, null,now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1989-08-22', 1, null, null, 'سید مصطفی', 'سید حسین ', 'عطائی کچوئی', '1160041148', null, null, '1160041148',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1999-06-09', 1, null, null, 'محمد رضا', 'علیرضا ', 'محمد رضایی', '1272946355', null, null, '1272946355',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1969-04-21', 1, 'اصفهان خیابان شریعتی کوچه ورپشتی ساختمان آدینه', null, 'حسین', 'محمد رضا', ' غروی', '4723667301', null, '1913943371', '14',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1963-12-22', 1, null, null, 'حسینعلی', 'بهمن ', 'ترکیان', '1142043721', null, null, null,now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1967-09-13', 1, null, null, 'علی', 'حسن', ' گندمکار', '5110181950', null, null, null,now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1962-03-28', 1, null, null, 'زلفعلی', 'حسن ', 'رضایی', '1582988544', null, null, '5',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1979-08-23', 1, 'اصفهان خیایان خاقانی بن بست فرزاد', null, 'محمود', 'علیرضا', ' یزدانی کچوئی', '1170104584', null, '8174745999', '10593',now(),1,now());
INSERT INTO public.person (birth_date, created_by, address, email, father_name, first_name, last_name, national_id, phone_number, postal_code, registration_number,created_date,last_modified_by,last_modified_date) VALUES ('1959-06-22', 1, null, null, 'مصطفی', 'علیرضا ', 'احمدی', '1285556607', null, null, null,now(),1,now());


