INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-19', 1, 1, 3, 'DELIVERED', 'معرفی اعضای هیئت مدیره', '1402/آ/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-10-18',  2, 1, 3, 'DELIVERED', 'درخواست صدور ضمانتنامه', '1402/آ/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-28',  3, 1, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/آ/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-12',  4, 1, 3, 'DRAFT', 'درخواست رسیدگی دفاتر', '1402/آ/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-02-01',  5, 1, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/آ/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-11',  6, 1, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/آ/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-12-08',  7, 1, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/آ/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-05-20',  8, 2, 3, 'DELIVERED', 'معرفی اعضای هیئت مدیره', '1402/م/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-02',  9, 2, 3, 'DELIVERED', 'درخواست صدور ضمانتنامه', '1402/م/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-12-23',  10, 2, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/م/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-27',  11, 2, 3, 'DELIVERED', 'درخواست رسیدگی دفاتر', '1402/م/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-08-25',  12, 2, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/م/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-02-06',  13, 2, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/م/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-10',  14, 2, 3, 'DRAFT', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/م/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-24',  1, 3, 3, 'DRAFT', 'معرفی اعضای هیئت مدیره', '1402/ف/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-02-10',  2, 3, 3, 'DRAFT', 'درخواست صدور ضمانتنامه', '1402/ف/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-10-21',  3, 3, 3, 'DRAFT', 'معرفی به بانک جهت دریافت وام', '1402/ف/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-11-28',  4, 3, 3, 'DELIVERED', 'درخواست رسیدگی دفاتر', '1402/ف/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-05-24',  5, 3, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/ف/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-10',  6, 3, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/ف/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-12-05',  7, 3, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/ف/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-10-24',  8, 4, 3, 'DELIVERED', 'معرفی اعضای هیئت مدیره', '1402/ی/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-16',  9, 4, 3, 'DELIVERED', 'درخواست صدور ضمانتنامه', '1402/ی/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-16',  10, 4, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/ی/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-10-14',  11, 4, 3, 'DELIVERED', 'درخواست رسیدگی دفاتر', '1402/ی/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-13',  12, 4, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/ی/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-12-02',  13, 4, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/ی/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-07',  14, 4, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/ی/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-01',  1, 5, 3, 'DRAFT', 'معرفی اعضای هیئت مدیره', '1402/پ/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-25',  2, 5, 3, 'DRAFT', 'درخواست صدور ضمانتنامه', '1402/پ/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-10-17',  3, 5, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/پ/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-08',  4, 5, 3, 'DELIVERED', 'درخواست رسیدگی دفاتر', '1402/پ/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-12-16',  5, 5, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/پ/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-07-28',  6, 5, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/پ/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-04',  7, 5, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/پ/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-02',  8, 6, 3, 'DELIVERED', 'معرفی اعضای هیئت مدیره', '1402/غ/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-15',  9, 6, 3, 'DELIVERED', 'درخواست صدور ضمانتنامه', '1402/غ/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-23',  10, 6, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/غ/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-02-08',  11, 6, 3, 'DRAFT', 'درخواست رسیدگی دفاتر', '1402/غ/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-10-03',  12, 6, 3, 'DRAFT', 'ارائه گزارش عملکرد', '1402/غ/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-01',  13, 6, 3, 'DRAFT', 'درخواست صدور مفاصا حساب', '1402/غ/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-01-13',  14, 6, 3, 'DRAFT', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/غ/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-08-27',  1, 7, 3, 'DRAFT', 'معرفی اعضای هیئت مدیره', '1402/خ/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-02-11',  2, 7, 3, 'DRAFT', 'درخواست صدور ضمانتنامه', '1402/خ/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-05-10',  3, 7, 3, 'DRAFT', 'معرفی به بانک جهت دریافت وام', '1402/خ/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-11-19',  4, 7, 3, 'DRAFT', 'درخواست رسیدگی دفاتر', '1402/خ/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-20',  5, 7, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/خ/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-11-08',  6, 7, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/خ/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-28',  7, 7, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/خ/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-05-27',  8, 8, 3, 'DELIVERED', 'معرفی اعضای هیئت مدیره', '1402/گ/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-20',  9, 8, 3, 'DELIVERED', 'درخواست صدور ضمانتنامه', '1402/گ/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-18',  10, 8, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/گ/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-08-13',  11, 8, 3, 'DELIVERED', 'درخواست رسیدگی دفاتر', '1402/گ/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-21',  12, 8, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/گ/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-26',  13, 8, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/گ/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-25',  14, 8, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/گ/7');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-05',  15, 9, 3, 'DELIVERED', 'معرفی اعضای هیئت مدیره', '1402/ک/1');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-09-09',  16, 9, 3, 'DELIVERED', 'درخواست صدور ضمانتنامه', '1402/ک/2');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-22',  17, 9, 3, 'DELIVERED', 'معرفی به بانک جهت دریافت وام', '1402/ک/3');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-06-02',  18, 9, 3, 'DELIVERED', 'درخواست رسیدگی دفاتر', '1402/ک/4');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-05',  19, 9, 3, 'DELIVERED', 'ارائه گزارش عملکرد', '1402/ک/5');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-04-22',  20, 9, 3, 'DELIVERED', 'درخواست صدور مفاصا حساب', '1402/ک/6');
INSERT INTO public.letter (creation_date, customer_id, company_id, year_id, letter_state, content, letter_number) VALUES ('2024-03-08',  21, 9, 3, 'DELIVERED', 'درخواست آزاد سازی ضمانتنامه حسن انجام کار', '1402/ک/7');
update public.letter set letter_type_id = 2;
