CREATE SEQUENCE IF NOT EXISTS _user_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS token_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE _user
(
    id        INTEGER NOT NULL,
    firstname VARCHAR(255),
    lastname  VARCHAR(255),
    username  VARCHAR(255),
    email     VARCHAR(255),
    password  VARCHAR(255),
    role      VARCHAR(255),
    enabled   BOOLEAN NOT NULL,
    CONSTRAINT pk__user PRIMARY KEY (id)
);

CREATE TABLE app_settings
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by           INTEGER,
    last_modified_by     INTEGER,
    created_date         TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date   TIMESTAMP WITHOUT TIME ZONE,
    max_upload_file_size BIGINT                                  NOT NULL,
    vsphere_url          VARCHAR(255),
    vsphere_username     VARCHAR(255),
    vsphere_password     VARCHAR(2048),
    backup_path          VARCHAR(1024),
    database_name        VARCHAR(255),
    CONSTRAINT pk_app_settings PRIMARY KEY (id)
);

CREATE TABLE attachment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR(255),
    file_type    VARCHAR(255),
    file_content OID,
    letter_id    BIGINT,
    deletable    BOOLEAN,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE board_member
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    person_id          BIGINT,
    company_id         BIGINT,
    position_id        BIGINT,
    CONSTRAINT pk_boardmember PRIMARY KEY (id)
);

CREATE TABLE company
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                INTEGER,
    last_modified_by          INTEGER,
    created_date              TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    tax_economic_code         VARCHAR(255),
    tax_file_number           VARCHAR(255),
    tax_file_class            VARCHAR(255),
    tax_trackingid            VARCHAR(255),
    tax_portal_username       VARCHAR(255),
    tax_portal_password       VARCHAR(255),
    tax_department            VARCHAR(255),
    company_name              VARCHAR(255),
    national_id               VARCHAR(255),
    registration_number       VARCHAR(255),
    registration_date         date,
    address                   VARCHAR(255),
    postal_code               VARCHAR(255),
    phone_number              VARCHAR(255),
    fax_number                VARCHAR(255),
    software_username         VARCHAR(255),
    software_password         VARCHAR(255),
    software_call_center      VARCHAR(255),
    insurance_portal_username VARCHAR(255),
    insurance_portal_password VARCHAR(255),
    insurance_branch          VARCHAR(255),
    letter_prefix             VARCHAR(255),
    letter_counter            INTEGER,
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    address            VARCHAR(255),
    phone_number       VARCHAR(255),
    national_identity  VARCHAR(255),
    register_code      VARCHAR(255),
    register_date      date,
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE document
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    document_name      VARCHAR(255),
    document_type      VARCHAR(255),
    file_extension     VARCHAR(255),
    document_file      OID,
    person_id          BIGINT,
    company_id         BIGINT,
    letter_id          BIGINT,
    CONSTRAINT pk_document PRIMARY KEY (id)
);

CREATE TABLE insurance_slip
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    issue_date         date                                    NOT NULL,
    slip_number        VARCHAR(255)                            NOT NULL,
    type               VARCHAR(255),
    amount             DECIMAL                                 NOT NULL,
    start_date         date                                    NOT NULL,
    end_date           date                                    NOT NULL,
    file               OID,
    file_extension     VARCHAR(255),
    file_name          VARCHAR(255),
    company_id         BIGINT                                  NOT NULL,
    CONSTRAINT pk_insuranceslip PRIMARY KEY (id)
);

CREATE TABLE letter
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    content            TEXT,
    creation_date      date,
    letter_type_id     BIGINT,
    letter_number      VARCHAR(255),
    customer_id        BIGINT,
    company_id         BIGINT,
    year_id            BIGINT,
    letter_state       VARCHAR(20),
    CONSTRAINT pk_letter PRIMARY KEY (id)
);

CREATE TABLE letter_type
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    type               VARCHAR(255),
    CONSTRAINT pk_lettertype PRIMARY KEY (id)
);

CREATE TABLE person
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by          INTEGER,
    last_modified_by    INTEGER,
    created_date        TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date  TIMESTAMP WITHOUT TIME ZONE,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    father_name         VARCHAR(255),
    national_id         VARCHAR(255),
    birth_date          date,
    registration_number VARCHAR(255),
    postal_code         VARCHAR(255),
    address             VARCHAR(255),
    phone_number        VARCHAR(255),
    email               VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE position
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    CONSTRAINT pk_position PRIMARY KEY (id)
);

CREATE TABLE sender
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    name               VARCHAR(255),
    address            VARCHAR(255),
    phone_number       VARCHAR(255),
    letter_prefix      VARCHAR(255),
    letter_counter     INTEGER,
    CONSTRAINT pk_sender PRIMARY KEY (id)
);

CREATE TABLE shareholder
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by                INTEGER,
    last_modified_by          INTEGER,
    created_date              TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date        TIMESTAMP WITHOUT TIME ZONE,
    person_id                 BIGINT,
    number_of_shares          INTEGER                                 NOT NULL,
    percentage_ownership      DECIMAL(5, 2)                           NOT NULL,
    share_price               DECIMAL(10, 2)                          NOT NULL,
    share_type                VARCHAR(255)                            NOT NULL,
    company_id                BIGINT,
    scanned_share_certificate OID,
    file_name                 VARCHAR(255),
    file_extension            VARCHAR(255),
    CONSTRAINT pk_shareholder PRIMARY KEY (id)
);

CREATE TABLE tax_payment_slip
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by         INTEGER,
    last_modified_by   INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    issue_date         date                                    NOT NULL,
    slip_number        VARCHAR(255)                            NOT NULL,
    type               VARCHAR(255),
    amount             DECIMAL                                 NOT NULL,
    period             VARCHAR(255)                            NOT NULL,
    company_id         BIGINT                                  NOT NULL,
    file               OID,
    file_extension     VARCHAR(255),
    file_name          VARCHAR(255),
    CONSTRAINT pk_taxpaymentslip PRIMARY KEY (id)
);

CREATE TABLE token
(
    id         INTEGER NOT NULL,
    token      VARCHAR(255),
    token_type VARCHAR(255),
    revoked    BOOLEAN NOT NULL,
    expired    BOOLEAN NOT NULL,
    user_id    INTEGER,
    CONSTRAINT pk_token PRIMARY KEY (id)
);

CREATE TABLE virtual_machine
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    ip_address VARCHAR(255),
    CONSTRAINT pk_virtualmachine PRIMARY KEY (id)
);

CREATE TABLE year
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_by             INTEGER,
    last_modified_by       INTEGER,
    created_date           TIMESTAMP WITHOUT TIME ZONE,
    last_modified_date     TIMESTAMP WITHOUT TIME ZONE,
    name                   BIGINT,
    starting_letter_number BIGINT,
    CONSTRAINT pk_year PRIMARY KEY (id)
);

ALTER TABLE _user
    ADD CONSTRAINT uc__user_username UNIQUE (username);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_LETTER FOREIGN KEY (letter_id) REFERENCES letter (id);

ALTER TABLE board_member
    ADD CONSTRAINT FK_BOARDMEMBER_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE board_member
    ADD CONSTRAINT FK_BOARDMEMBER_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE board_member
    ADD CONSTRAINT FK_BOARDMEMBER_ON_POSITION FOREIGN KEY (position_id) REFERENCES position (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_LETTER FOREIGN KEY (letter_id) REFERENCES letter (id);

ALTER TABLE document
    ADD CONSTRAINT FK_DOCUMENT_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE insurance_slip
    ADD CONSTRAINT FK_INSURANCESLIP_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customer (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_LETTER_TYPE FOREIGN KEY (letter_type_id) REFERENCES letter_type (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_YEAR FOREIGN KEY (year_id) REFERENCES year (id);

ALTER TABLE shareholder
    ADD CONSTRAINT FK_SHAREHOLDER_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE shareholder
    ADD CONSTRAINT FK_SHAREHOLDER_ON_PERSON FOREIGN KEY (person_id) REFERENCES person (id);

ALTER TABLE tax_payment_slip
    ADD CONSTRAINT FK_TAXPAYMENTSLIP_ON_COMPANY FOREIGN KEY (company_id) REFERENCES company (id);

ALTER TABLE token
    ADD CONSTRAINT FK_TOKEN_ON_USER FOREIGN KEY (user_id) REFERENCES _user (id);