CREATE TABLE attachment
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    file_name    VARCHAR(255),
    file_type    VARCHAR(255),
    file_content OID,
    letter_id    BIGINT,
    deletable    BOOLEAN,
    CONSTRAINT pk_attachment PRIMARY KEY (id)
);

CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

CREATE TABLE company
(
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tax_economic_code         VARCHAR(255),
    tax_file_number           VARCHAR(255),
    tax_file_class            VARCHAR(255),
    tax_trackingid            VARCHAR(255),
    tax_portal_username       VARCHAR(255),
    tax_portal_password       VARCHAR(255),
    tax_department            VARCHAR(255),
    company_name              VARCHAR(255),
    national_id               VARCHAR(255),
    registration_number       VARCHAR(255),
    registration_date         date,
    address                   VARCHAR(255),
    postal_code               VARCHAR(255),
    phone_number              VARCHAR(255),
    fax_number                VARCHAR(255),
    software_username         VARCHAR(255),
    software_password         VARCHAR(255),
    software_call_center      VARCHAR(255),
    insurance_portal_username VARCHAR(255),
    insurance_portal_password VARCHAR(255),
    insurance_branch          VARCHAR(255),
    CONSTRAINT pk_company PRIMARY KEY (id)
);

CREATE TABLE letter
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content       TEXT,
    creation_date date,
    letter_number VARCHAR(255),
    recipient_id  BIGINT,
    sender_id     BIGINT,
    year_id       BIGINT,
    letter_state  VARCHAR(20),
    CONSTRAINT pk_letter PRIMARY KEY (id)
);

CREATE TABLE person
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name          VARCHAR(255),
    last_name           VARCHAR(255),
    father_name         VARCHAR(255),
    national_id         VARCHAR(255),
    birth_date          date,
    registration_number VARCHAR(255),
    postal_code         VARCHAR(255),
    address             VARCHAR(255),
    CONSTRAINT pk_person PRIMARY KEY (id)
);

CREATE TABLE products
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    description        VARCHAR(255)                            NOT NULL,
    price              DECIMAL                                 NOT NULL,
    category_id        BIGINT,
    created_by         INTEGER,
    created_date       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_by   INTEGER,
    last_modified_date TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_products PRIMARY KEY (id)
);

CREATE TABLE customer
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(255),
    address           VARCHAR(255),
    phone_number      VARCHAR(255),
    national_identity VARCHAR(255),
    register_code     VARCHAR(255),
    register_date     date,
    CONSTRAINT pk_recipient PRIMARY KEY (id)
);

CREATE TABLE sender
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name           VARCHAR(255),
    address        VARCHAR(255),
    phone_number   VARCHAR(255),
    letter_prefix  VARCHAR(255),
    letter_counter INTEGER,
    CONSTRAINT pk_sender PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    id INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE year
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name BIGINT,
    CONSTRAINT pk_year PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_categories_name UNIQUE (name);

ALTER TABLE letter
    ADD CONSTRAINT uc_letter_letter_number UNIQUE (letter_number);

ALTER TABLE attachment
    ADD CONSTRAINT FK_ATTACHMENT_ON_LETTER FOREIGN KEY (letter_id) REFERENCES letter (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES customer (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_SENDER FOREIGN KEY (sender_id) REFERENCES sender (id);

ALTER TABLE letter
    ADD CONSTRAINT FK_LETTER_ON_YEAR FOREIGN KEY (year_id) REFERENCES year (id);

ALTER TABLE products
    ADD CONSTRAINT FK_PRODUCTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);